/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack;
import java.util.Stack;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Stack<Integer> objStack = new Stack<Integer>();
        objStack.push(10);
        objStack.push(20);
        System.out.println(objStack.peek());

        objStack.push(100);
        System.out.println(objStack.peek());

        System.out.println(objStack.pop());
        System.out.println(objStack.peek());

        System.out.println(objStack.pop());
        System.out.println(objStack.pop());
        //System.out.println(objStack.pop());
    }
}
