/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tablahash;

import java.util.Map.Entry;
import java.util.HashMap;
import java.util.Hashtable;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        HashMap<String, Integer> objHashMap = new HashMap<>();
        objHashMap.put("var1",10);
        objHashMap.put("var2",20);
        objHashMap.put("var3",40);
        objHashMap.put("var4",50);
        System.out.println(objHashMap);

        for (String key : objHashMap.keySet()) {
            System.out.println(key);
        }

        for (Integer value : objHashMap.values()){
            System.out.println(value);
        }

        for (Entry<String,Integer> v : objHashMap.entrySet()) {
            System.out.println(v.getValue()+ " " + v.getKey());
        }

        Hashtable<String, Integer> objHashTable = new Hashtable();
        objHashTable.put("x",10);
        objHashTable.put("y",20);
        System.out.println(objHashTable);
    }
}
