/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package brt;


public class App {
    public void getGreeting() {
        Nodo x = new Nodo(2);
        Nodo r = new Nodo(3);
        Nodo l = new Nodo(1);
        l.setPadre(x);
        r.setPadre(x);
        x.setHIzq(l);
        x.setHDer(r);
        System.out.println(x);
    }
    public void prueba() {
      Nodo r = new Nodo(8);
      Nodo l = new Nodo(5);
      l.setPadre(r);
      r.setHIzq(l);

      Nodo d = new Nodo(9);
      d.setPadre(r);
      r.setHDer(d);

      Nodo ll = new Nodo(1);
      ll.setPadre(l);
      l.setHIzq(ll);

      Nodo ld = new Nodo(6);
      ld.setPadre(l);
      l.setHDer(ld);

      BRT arbol1 = new BRT();
      arbol1.setRaiz(r);

      System.out.println(arbol1);
      arbol1.rotacion_derecha(r);
      System.out.println(arbol1);
      arbol1.rotacion_izquierda(l);
      System.out.println(arbol1);
          
    }
    public void pruebaEjemplo1() {
      Nodo n2 = new Nodo(2);
      Nodo n1 = new Nodo(1);
      n1.setPadre(n2);
      n2.setHIzq(n1);

      Nodo n4 = new Nodo(4);
      n4.setPadre(n2);
      n2.setHDer(n4);

      Nodo n3 = new Nodo(3);
      n3.setPadre(n4);
      n4.setHIzq(n3);

      Nodo n5 = new Nodo(5);
      n5.setPadre(n4);
      n4.setHDer(n5);

      BRT arbolA = new BRT();
      arbolA.setRaiz(n2);
      System.out.println(arbolA);
      arbolA.rotacion_izquierda(n4);
      System.out.println(arbolA);
      arbolA.rotacion_derecha(n5);
      System.out.println(arbolA);
      //Rotación sobre el 2
      arbolA.rotacion_izquierda(n2);
      System.out.println(arbolA);
      arbolA.rotacion_derecha(n4);
      arbolA.rotacion_derecha(n2);
      System.out.println(arbolA);
      try {
        arbolA.rotacion_derecha(n1);
      }
      catch(Exception e) {
        System.out.println(e.getMessage());
      }

    }
    public static void main(String[] args) {
        App obj = new App();
        obj.getGreeting();
        obj.prueba();
        obj.pruebaEjemplo1();
        
            
    }
}
