/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quicksort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;


class QuickSortTest{ 
    @Test
    void testParticion() {
      QuickSort objQuicksort = new QuickSort();
      int arr[] = {5,1,8,4,9,3,7,6};
      int q = objQuicksort.particion(arr,0,arr.length-1);
      assertEquals(2, q);
      int expected[] = {3,1,4,8,9,5,7,6};
      assertArrayEquals(expected, arr);
    }

    @Test
    void testParticionCase2() {
      QuickSort objQuicksort = new QuickSort();
      int arr[] = {1,10,9,3,2,8,3,9};  
      int q = objQuicksort.particion(arr,0,arr.length-1);
      assertEquals(0, q);
      int expected[] = {1,10,9,3,2,8,3,9};
      assertArrayEquals(expected, arr);
    }

    @Test
    void testParticionCase3() {
      QuickSort objQuicksort = new QuickSort();
      int arr[] = {10,1,9,3,2,8,3,7};  
      int q = objQuicksort.particion(arr,0,arr.length-1);
      assertEquals(6, q);
      int expected[] = {7,1,9,3,2,8,3,10};
      assertArrayEquals(expected, arr);
    }

    @Test
    void sortCase1(){
      
      QuickSort objQuicksort = new QuickSort();
      int arr[] = {5,1,8,4,9,3,7,6};
      objQuicksort.sort(arr,0,arr.length-1);
      int expected[] = {1,3,4,5,6,7,8,9};
      assertArrayEquals(expected, arr);
    }

    @Test
    void sortCase2() {
      QuickSort objQuicksort = new QuickSort();
      int arr[] = {1,10,9,3,2,8,3,9};  
      objQuicksort.sort(arr,0,arr.length-1);
      int expected[] = {1,2,3,3,8,9,9,10};
      assertArrayEquals(expected, arr);
    }

    @Test
    void sortCase3() {
      QuickSort objQuicksort = new QuickSort();
      int arr[] = {10,1,9,3,2,8,3,7};  
      objQuicksort.sort(arr,0,arr.length-1);
      int expected[] = {1,2,3,3,7,8,9,10};
      assertArrayEquals(expected, arr);
    }

    @Test
    void sortCaseN() {
        QuickSort objQuicksort = new QuickSort();
        for (int i =0; i<10000; i++) {
            int arr[] = new int[10000];
            for (int j = 0; j<10000; j++) {
                arr[j] = (int) (Math.random()*100000);
            }
            int sorted[] = arr.clone();
            Arrays.sort(sorted);
            objQuicksort.sort(arr,0,arr.length-1);
            assertArrayEquals(sorted, arr);
        }
    }

    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
