/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tablashash;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.Map;
import java.util.stream.Collectors;
public class App {
    public void ejemplo() {
      HashMap<String, Integer> map = new HashMap<String, Integer>();
      map.put("uno", 1);
      map.put("uno", 2);
      map.put("dos", 2);
      map.put("tres", 3);
      map.put("cuatro", 4);
      map.put("cinco", 5);
      map.put("seis", 6);
      map.put("siete", 7);
      System.out.println(map);
      for(String key : map.keySet()) {
        System.out.println(key + " " + map.get(key));
      }
      for(Integer value : map.values()) {
        System.out.println(value);
      }
      for(HashMap.Entry<String, Integer> entry : map.entrySet()) {
        System.out.println(entry.getKey() + " " + entry.getValue());
      }
      System.out.println(map.get("perrito"));
      //Elevar al cuadrado y guardar en map2 
      Map<Object,Object> map2 = map.entrySet().stream().collect(Collectors.toMap(
        entry -> entry.getKey().toUpperCase(),
        entry -> entry.getValue() * entry.getValue()
      ));
      System.out.println(map2);
    }


    public static void main(String[] args) {
      App app = new App();
      app.ejemplo();
    }
}
