/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ordenamiento;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class BucketSortTest{ 
    @Test void pruebaMortal() {
        BucketSort bs = new BucketSort();
        for (int i=0; i<1000; i++) {
          double arr[] = new double[1000];
          for (int j=0; j<1000; j++) {
            arr[j] = Math.random();
          }
          bs.sort(arr);
          for (int j=0; j<arr.length-1; j++) {
            assertTrue(arr[j] <= arr[j+1]);
          }
        }
    }
}
